### ISSUE TITLE
Update RBAC

### ISSUE THREAD

**Issue by bryanpaget** [StatCan/namespace-cleaner#16]
Need to update RBAC because the app will need to get secrets and apply get and labels.

- Add secrets
- Need to update labels on the cluster — add those verbs and objects
- Might need to change RoleBinding to ClusterRoleBinding

**Comment by bryanpaget** [comment]
I have updated the RBAC to allow more verbs on more objects:

``` yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-cleaner
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-cleaner-bind
subjects:
  - kind: ServiceAccount
    name: namespace-cleaner
    namespace: das
roleRef:
  kind: ClusterRole
  name: namespace-cleaner
  apiGroup: rbac.authorization.k8s.io
```
